name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      packages: write # needed for pushing the images to ghcr.io

    env:
      GO111MODULE: on
      COSIGN_EXPERIMENTAL: "true"

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Tejolote
        uses: kubernetes-sigs/release-actions/setup-tejolote@a69972745f85aab4ba5d6c681e2a0e7f73eaff2b # v0.3.0

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Get TAG
        id: tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: TmpDir
        id: tmpdir
        run: |
          TMP_DIR=$(mktemp -d ${HOME}/.build.XXXXXX )
          echo "TMP_DIR=${TMP_DIR}" >> $GITHUB_OUTPUT

      - name: Build
        id: run-build
        run: |
          go build -o "${{ steps.tmpdir.outputs.TMP_DIR }}/hello-linux-amd64" . 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        uses: kubernetes-sigs/release-actions/publish-release@a69972745f85aab4ba5d6c681e2a0e7f73eaff2b # v0.3.0
        with:
            assets: "${{ steps.tmpdir.outputs.TMP_DIR }}/hello-linux-amd64"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup bnd
        uses: carabiner-dev/bnd-actions/setup@HEAD

      - name: Setup unpack
        uses: carabiner-dev/actions/install/unpack@HEAD

      - name: Generate SBOM
        run:
          unpack extract . --ignore-other-codebases -f spdx --attest > spdx.intoto.json
          unpack extract . --ignore-other-codebases -f spdx > ${{ github.event.repository.name }}-${{ steps.tag.outputs.TAG }}.spdx.json
          unpack extract . --ignore-other-codebases -f cyclonedx > ${{ github.event.repository.name }}-${{ steps.tag.outputs.TAG }}.cdx.json

      - run: |
          tejolote attest --artifacts github://${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/${{ steps.tag.outputs.TAG }} github://${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}"/${{ github.run_id }}" --output slsa.intoto.json 
          cat slsa.intoto.json
          bnd statement slsa.intoto.json --out slsa.bundle.json

      - name: Attest Security Insights
        id: attest-si
        run: |
          bnd commit --predicate-git-path=SECURITY-INSIGHTS.yml --yaml --repo . > si.bundle.json
          cat si.bundle.json

      - name: Pack Attestations
        id: pack-attestations
        run: |
          bnd pack si.bundle.json slsa.bundle.json spdx.intoto.json > attestations.jsonl

      - name: upload-attestation
        id: upload-release-asset 
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files:
              attestations.jsonl
              ${{ github.event.repository.name }}-${{ steps.tag.outputs.TAG }}.spdx.json
              ${{ github.event.repository.name }}-${{ steps.tag.outputs.TAG }}.cdx.json
          tag_name: "${{ steps.tag.outputs.TAG }}"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: ${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}
